export const logo = "https://upload.wikimedia.org/wikipedia/commons/0/05/Facebook_Logo_%282019%29.png"
export const avatar = "https://static2.yan.vn/YanNews/2167221/202102/facebook-cap-nhat-avatar-doi-voi-tai-khoan-khong-su-dung-anh-dai-dien-e4abd14d.jpg"
export const friends = "https://static.xx.fbcdn.net/rsrc.php/v3/y8/r/S0U5ECzYUSu.png"
export const community = "https://static.xx.fbcdn.net/rsrc.php/v3/y5/r/PrjLkDYpYbH.png"
export const market = "https://static.xx.fbcdn.net/rsrc.php/v3/yU/r/D2y-jJ2C_hO.png"
export const watch = "https://static.xx.fbcdn.net/rsrc.php/v3/y5/r/duk32h44Y31.png"
export const memory = "https://static.xx.fbcdn.net/rsrc.php/v3/y5/r/duk32h44Y31.png"
export const postImg = "https://lh3.googleusercontent.com/15l5xEt2GHnTdkprBsXp-BavgQf8qsCpYWq4G4F1gp-oopRadmMZHeXVCl-ck1DFdI9qtAf4XcBbNjRxIE30Q7F67Fg43us9m6d98lI1GOsu1cZv5pJvJ6JYCZHpHRQVeHbo1HcL"